### ISSUE TITLE
Sass(SCSS) not compiling properly in production build

### ISSUE THREAD

**Issue by trvswgnr** [alexnoz/webpack-pug-scss-boilerplate#1]
Webpack doesn't seem to be compiling the SCSS properly when running the production build. When I'm running the development server everything is fine, but in production when I do basic Sass features like nesting it doesn't seem to register.

Maybe (but probably not) related: the font files give 404 errors in production. The path says /fonts/ is in /build/styles/, but it should be directly in the build folder.

**Comment by alexnoz** [comment]
Sorry for the delayed response @trvswgnr , and thanks for the issue. It was a problem with purify-css, it stripped out all the CSS rules that weren't used in JS, it should be fixed now (as well as the 404 response).
