### ISSUE TITLE
How to use your boilerplate, it's always fail

### ISSUE THREAD

**Issue by loicroux69** [alexnoz/webpack-pug-scss-boilerplate#17]
How do you manage to get a multipage website with MIME type supported, chunks and variables in the template compiled files. Do you have a correct webpack config for that.

I'm a beginner i don't understand all of your code...
Thanks for helping.

**Comment by alexnoz** [comment]
Do you have any console errors when running npm scripts?

**Comment by loicroux69** [comment]
Yes never the same actually the bug is from the bundle.js file, the file never builded.

The error code is strange, i can't install the dependency, the npm installation always fail at about 75%.
```
This dependency was not found:

* /Users/loic/Desktop/Workspace/Sites/app-goulgoure/webpack-pug-scss-boilerplate/app in multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./ap
p

To install it, you can run: npm install --save /Users/loic/Desktop/Workspace/Sites/app-goulgoure/webpack-pug-scss-boilerplate/app
```

**Comment by alexnoz** [comment]
This is strange, could you show your webpack config? Also, please show the output from `tree ./app` command ( run it from your project's root directory) and from `npm ls --depth=0`.

**Comment by loicroux69** [comment]
I just reach to get rid of this error but the page launched by server is the wrong one. 
The contact is launched instead of index.

`tree ./app`
[
<img width="348" alt="capture d ecran 2019-02-11 a 23 18 38" src="https://user-images.githubusercontent.com/47380500/52597515-6f8a2b00-2e53-11e9-8e1e-592627619916.png">
](url)

`npm ls --depth=0`

<img width="1114" alt="capture d ecran 2019-02-11 a 23 20 44" src="https://user-images.githubusercontent.com/47380500/52597612-b37d3000-2e53-11e9-8f2d-36e67147e079.png">

**Comment by loicroux69** [comment]
Sorry i give up this boilerplate is too high level for me i juste made crash another time my project...
