### ISSUE TITLE
How do you make more pages?

### ISSUE THREAD

**Issue by CodeDraken** [alexnoz/webpack-pug-scss-boilerplate#2]
How do you create more pages, like index.pug? I haven't used Pug much before so sorry if this should be obvious :sweat_smile:

**Comment by alexnoz** [comment]
There is [an abstraction](https://github.com/alexnoz/webpack-pug-scss-boilerplate/blob/master/webpack.parts.js#L273) for that in `webpack.parts.js` file. 
So, assuming you have the following folder structure:
```
app
|__index.pug
|__index.js
|__about
|    |__about.pug
|    |__index.js
|
...
```
The [export part](https://github.com/alexnoz/webpack-pug-scss-boilerplate/blob/master/webpack.config.js#L170) of `webpack.config.js` would look something like this:
```js
module.exports = env => {
  const pages = [
    parts.page({
      title: 'Home',
      entry: {
        home: PATHS.app
      },
       
      // `manifest` and `vendor` are shared between all pages
      chunks: ['home', 'manifest', 'vendor']
    }),
    parts.page({
      title: 'About',
      path: 'about',
      entry: {
        about: path.join(PATHS.app, 'about/index.js')
      },
      
      // `manifest` and `vendor` are shared between all pages
      chunks: ['about', 'manifest', 'vendor']
    })
  ];

  const config = env === 'production' ?
    productionConfig :
    developmentConfig;

  return merge([commonConfig, config].concat(pages));
};
```
Then, in all `index.js` files:
```js
// for live reloading
if (process.env.NODE_ENV !== 'production') {
  require('./path/to/page.pug');
}
```
Also, you would want to remove `HtmlPlugin` from [commonConfig](https://github.com/alexnoz/webpack-pug-scss-boilerplate/blob/master/webpack.config.js#L57).

**Comment by wender** [comment]
@alexnoz  My Styles are not being included this way, would it be some other "chunk" on the array? If so, what would it be?

**Comment by alexnoz** [comment]
@wender you have to import them in your `index.js` files for every page, see [index.js](https://github.com/alexnoz/webpack-pug-scss-boilerplate/blob/master/app/scripts/index.js) from the repo

**Comment by wender** [comment]
@alexnoz Got it, thanks
