### ISSUE TITLE
Modern web development

### ISSUE THREAD

**Issue by Doogiemuc** [alexnoz/webpack-pug-scss-boilerplate#23]
When you install this boilerplate and do a

    npm install

you end up with 154 MB of code (including node_modules dir).

Of course this is not a bug of this repository in no way. In a philosophical sense it could be seen as a question: Where did we end up with modern web development?!?!?? 

(Sorry, just couldn't resist. Had to post this)

**Comment by alexnoz** [comment]
Hello @Doogiemuc, sorry for the delayed response. Webpack and other bundlers do their job well, eliminating everything that isn't needed in production and compressing/optimising all the rest, so it's not really an issue for the end user, and that's what matters the most - how much of that code end up in the final production bundle and reach the user. Most of this code is needed only for development purposes. All these tools greatly improve DX and speed up the process of creating an app, making it ergonomic as never before. I think there will always be a tradeoff between DX and developer efficiency on one hand vs. the amount of tools that you use (hence `node_modules/`, `go/pkg/` or `.cargo/` bloat) on the other. For now, all we can do is to keep learning and trying our best to improve the current situation 🙂
